stages:
  preprocess:
    cmd: python3 src/spacetitanic/features/preprocess.py
    deps:
    - data/raw
    - src/spacetitanic/features/preprocess.py
    outs:
    - data/processed/train_test_preprocessed.csv
  engineer:
    cmd: python3 src/spacetitanic/features/engineer.py
    deps:
    - data/processed/train_test_preprocessed.csv
    - src/spacetitanic/features/engineer.py
    outs:
    - data/processed/test_engineered.csv
    - data/processed/train_engineered.csv
  train:
    cmd: python3 src/spacetitanic/models/train.py
    deps:
    - data/processed/train_engineered.csv
    - src/spacetitanic/models/train.py
    outs:
    - data/processed/val_engineered.csv
    - model/model_test.joblib
    - model/model_val.joblib
  evaluate:
    cmd: python3 src/spacetitanic/models/evaluate.py
    deps:
    - data/processed/test_engineered.csv
    - data/processed/val_engineered.csv
    - model/model_test.joblib
    - model/model_val.joblib
    - src/spacetitanic/models/evaluate.py
    outs:
    - data/output/submission.csv
    metrics:
    - metrics/metrics.json:
        cache: false
